
package question2;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author lab_services_student
 */
public class EstateAgentReport extends javax.swing.JFrame {

    private final IEstateAgent estateAgent = new EstateAgent();
    /**
     * Creates new form EstateAgentReport
     */
    public EstateAgentReport() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgentLocation = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        lblPropertyPrice = new javax.swing.JLabel();
        lblCommissionPercentage = new javax.swing.JLabel();
        lblAgentReport = new javax.swing.JLabel();
        cbxLocation = new javax.swing.JComboBox<>();
        txtAgentName = new javax.swing.JTextField();
        txtPropertyPrice = new javax.swing.JTextField();
        txtCommissionPercentage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miProcessReport = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgentLocation.setText("AGENT LOCATION:");

        lblAgentName.setText("ESTATE AGENT NAME:");

        lblPropertyPrice.setText("PROPERTY PRICE:");

        lblCommissionPercentage.setText("COMMISSION PERCENTAGE:");

        lblAgentReport.setText("ESTATE AGENT REPORT:");

        cbxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "and Pretoria" }));
        cbxLocation.setToolTipText("");
        cbxLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxLocationMouseClicked(evt);
            }
        });
        cbxLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLocationActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jMenu1.setText("File");

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        miProcessReport.setText("Process Report");
        miProcessReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProcessReportActionPerformed(evt);
            }
        });
        jMenu2.add(miProcessReport);

        jMenuItem2.setText("Clear");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Save Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgentLocation)
                            .addComponent(lblAgentName)
                            .addComponent(lblPropertyPrice)
                            .addComponent(lblCommissionPercentage)
                            .addComponent(lblAgentReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxLocation, 0, 125, Short.MAX_VALUE)
                            .addComponent(txtAgentName)
                            .addComponent(txtPropertyPrice)
                            .addComponent(txtCommissionPercentage))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentLocation)
                    .addComponent(cbxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentName)
                    .addComponent(txtAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropertyPrice)
                    .addComponent(txtPropertyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCommissionPercentage)
                    .addComponent(txtCommissionPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblAgentReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLocationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxLocationActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        int yesNoOption = JOptionPane.YES_NO_OPTION;
        int optionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit.", "Exit", yesNoOption);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void miProcessReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProcessReportActionPerformed
        // TODO add your handling code here:
        String location = this.cbxLocation.getSelectedItem().toString();
        String agentName = this.txtAgentName.getText();
        String propertyPrice = this.txtPropertyPrice.getText();
        String commissionPercentage = this.txtCommissionPercentage.getText();
        
        double calculatedCommission = Double.parseDouble(commissionPercentage);
        
        String displayText =("AGENT LOCATION: " + location +
                             "\nAGENT NAME: " + agentName +
                             "\nPROPERTY PRICE: R " + propertyPrice +
                             "\nCOMMISSION PERCENTAGE: " + Double.parseDouble(commissionPercentage) + "%" +
                             "\nCALCULATED COMMISSION: R " + calculatedCommission);
        
        txtArea.setText(displayText);
        
    }//GEN-LAST:event_miProcessReportActionPerformed

    private void processReport() {
        String agentLocation = (String) cbxLocation.getSelectedItem();
        String agentName = txtAgentName.getText();
        double propertyPrice = Double.parseDouble(txtPropertyPrice.getText());
        double agentCommission = Double.parseDouble(txtCommissionPercentage.getText());

        if (estateAgent.validateData(agentLocation, agentName, propertyPrice, agentCommission)) {
            double commission = estateAgent.calculateCommission(propertyPrice, agentCommission);
            String report = String.format("Location: %s\nAgent: %s\nProperty Price: %.2f\nCommission Percentage: %.2f%%\nCommission Earned: %.2f",
                    agentLocation, agentName, propertyPrice, agentCommission, commission);
            reportTextArea.setText(report);
        } else {
            JOptionPane.showMessageDialog(frame, "Invalid data. Please check your input.");
        }
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        String reportText = txtArea.getText();
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("report.txt"))) {
            writer.write(reportText);
            JOptionPane.showMessageDialog(null, "Report saved to report.txt", "Save Report", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error saving report", "Save Report", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        cbxLocation.setSelectedIndex(0);
        txtAgentName.setText("");
        txtPropertyPrice.setText("");
        txtCommissionPercentage.setText("");
        txtArea.setText("");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cbxLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxLocationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLocationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EstateAgentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxLocation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgentLocation;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblAgentReport;
    private javax.swing.JLabel lblCommissionPercentage;
    private javax.swing.JLabel lblPropertyPrice;
    private javax.swing.JMenuItem miProcessReport;
    private javax.swing.JTextField txtAgentName;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtCommissionPercentage;
    private javax.swing.JTextField txtPropertyPrice;
    // End of variables declaration//GEN-END:variables

    
}

//Java Programming, Ninth Edition. In: Java Programming, Ninth Edition.
// Farrell, J., 2012.
// pp 1 - 833

//https://www.youtube.com/watch?v=Zs342ePFvRI
//Java inheritence👪
//Bro Code


